/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timer;

import java.awt.Label;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author user6
 */
public class NewJFrame extends javax.swing.JFrame {
    public static int time = 0;
    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        spnMinute = new javax.swing.JSpinner();
        spnHour = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        lblMensaje = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblMensaje1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(spnMinute, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 60, -1));
        getContentPane().add(spnHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 60, -1));
        spnHour.getAccessibleContext().setAccessibleName("");

        jButton1.setText("Set");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, -1, -1));

        lblMensaje.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 0, 153));
        getContentPane().add(lblMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 310, 30));
        lblMensaje.getAccessibleContext().setAccessibleName("");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblTime.setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().add(lblTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 40));

        lblMensaje1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblMensaje1.setForeground(new java.awt.Color(255, 0, 153));
        getContentPane().add(lblMensaje1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 310, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    static JLabel getlblTimer(){
        return lblTime;
    } 
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int hours = (int)spnHour.getValue();
        int minutes = (int)spnMinute.getValue();
        time = 60*60*hours + minutes*60;
        Tiempo temp = new Tiempo();
        temp.start();
        lblMensaje1.setText("Su PC se apagará en ");
        lblMensaje.setText("segundos.");


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    public static javax.swing.JLabel lblMensaje;
    public static javax.swing.JLabel lblMensaje1;
    public static javax.swing.JLabel lblTime;
    private javax.swing.JSpinner spnHour;
    private javax.swing.JSpinner spnMinute;
    // End of variables declaration//GEN-END:variables
}
